Add method to get Notepad++ version
kbilsted/NotepadPlusPlusPluginPack.Net pull request #100
Opened 2022-12-04 23:47 UTC by gandarez

This PR adds a method to retrieve the full version from Notepad++ like ` 8.4.7`.

2022-12-05 19:55 UTC, kbilsted requested changes

2022-12-05 20:11 UTC, gandarez commented on Visual Studio Project Template C#/PluginInfrastructure/NotepadPPGateway.cs
> +                var high = num >> 16;
What exactly is weird? I didn't get you

2023-01-12 16:14 UTC, gandarez commented
Any thoughts?

2023-02-11 17:59 UTC, gandarez commented
Hello?

2023-03-13 19:18 UTC, oSerenity approved these changes

2023-04-26 01:03 UTC, molsonkiko commented
IMO it would be better for a `GetNppVersion` method to return a 2-int array containing (major, minor*10 + bugfix) or a 3-int array containing (major, minor, bugfix).
Returning an int array is more useful because the user doesn't need to parse a string to get the major, minor, or bugfix version. 

```
/// <summary>
/// 3-int array: {major, minor, bugfix}<br></br>
/// Thus GetNppVersion() would return {8, 5, 0} for version 8.5.0
/// and {7, 7, 1} for version 7.7.1
/// </summary>
/// <returns></returns>
public int[] GetNppVersion()
{
    int version = Win32.SendMessage(PluginBase.nppData._nppHandle, (uint)NppMsg.NPPM_GETNPPVERSION, 0, 0).ToInt32();
    int major = version >> 16;
    int minor = Math.DivRem(version & 0xffff, 10, out int bugfix);
    return new int[] { major, minor, bugfix };
}
```

2023-11-07 17:42 UTC, closed without merging